### PR TITLE
Added Postman Collection

### PR DESCRIPTION
**Pull request by emanuelvintila**

### CODE REVIEW

**Comment by sgurusamy-rli** [comment]
@emanuelvintila 
Please find my review comments for the collection below:

1. Structure Changes:
	- Rename Negative Tests -> Validations
	- Under each flows, create folders for endpoints Authorize and Token based on type of flow. Say, id_token flow will have only Authorization.
	-  Group Common validations of all flows and make sure each of the flow executes these validations. (Suggested approach, move the common validation requests as separate folder and call these requests from Tests section of each of the flows folder)
2. Still some of the Invalid responses checks for Status 200. (review all the requests and make sure this is updated for all the requests which are checking for respective invalid status and errors).
3. Invalid Response Refresh Token, requests for Refresh Tokens parameters are incorrect or not requesting for refresh tokens.
4. Audience validation missing.
5. Positive tests are missing verification of items inside token, like expiration, issuer, audience, nbf...
6. Resource Owner password flow verify and add requests for positive and negative tests
7. User Info, endpoint to be used for tests to verify positive and negative cases to validate the token received and information received under this endpoint is based on the value sent in scope.
8. Add a request to openId configuration endpoint and add a test to confirm the expected presence of values.
9. Have all example requests be updated with proper values, avoid localhost and other debug values.
10. Add validations/verification tests for EndSession requests.
11. Add request and tests to include Revoke application.

**Comment by emanuelvintila** [comment]
1\.
> move the common validation requests as separate folder and call these requests from Tests section of each of the flows folder

not quite doable with the way we have currently set up the collection and the tests. But these kind of requests already happen as part of testing a token's validity.
image


3\. Can you be more clear? This request would return a refresh token as well, and we're pretending we got an invalid one in the post request script.
image

4 & 5\. Most of the claims are validated for every token received, including "aud"
image

6\. Resource Owner Password Credentials flow is not implemented in CFS
image

10\. EndSession will be tested by the standalone application

**Comment by sgurusamy-rli** [comment]
> 1.
> 
> > move the common validation requests as separate folder and call these requests from Tests section of each of the flows folder
> 
> not quite doable with the way we have currently set up the collection and the tests. But these kind of requests already happen as part of testing a token's validity. image
> 
`ok, I see execution of tests from differnt folder is little tricky. Can we have the common validation tests grouped by flows which takes all the values as same? Say, Validations->Authorize->All - Will have invalid_client_id tests for all the flows and Validations->Token->AuthCodeAndAuthCodePKCEFlow will have tests common to validate token for Authcode and AuthCodePKCEFlow. With this you can move the Validations as a top level folder and all the flows folder will have positive tests and we will not repeat these validation tests for each flow.`
> 3. Can you be more clear? This request would return a refresh token as well, and we're pretending we got an invalid one in the post request script. image
> 
`The one highlighted in your image is not the referenced request. I was refering to the "Refresh Token" request you have as separate. And can you add a request to get a new token using refreshToken?`
image



> 4 & 5. Most of the claims are validated for every token received, including "aud" image
> 
`Thanks for confirming. `
> 6. Resource Owner Password Credentials flow is not implemented in CFS image
> 
`Can you verify this on the code and confirm again? I see code has some references to ResourceOwnerPassword (AccessTokenResourceOwnerPasswordCredentialsRequest, this is one of the class which process therequest), verify the path and confirm why we get grant type error possibly some invalid or missing params. `
image

> 10. EndSession will be tested by the standalone application
`Got it, the standalone application will cover these cases.`


Let me know if you like to discuss and clarify further.

**Comment by emanuelvintila** [comment]
1\. I don't see how this helps with avoiding duplicates. For example, for the case with invalid client_id, there will still be a request for the Authorization code flow, and a separate one for Authorization code flow with PKCE, both expecting an error of type invalid_client. The only difference is that now they're grouped by the validation type instead of the flow type. Is that what you're expecting, or if not can you give a more detailed example of grouping these validations?

3\. I'm not sure what you mean, the response from that request contains an access token as well as a refresh token.
image

Both `grant_type=authorization_code` and `grant_type=refresh_token` grant access tokens and refresh tokens, but their input is different, for one you need the authorization code returned from the /authorize endpoint, respectively for the other you need a refresh token returned from the /token endpoint in specific cases (for example you won't get a refresh token when calling the /token endpoint with `grant_type=client_credentials`

6\. This is the code that throws the exception
image
and is then caught returning `unsupported_grant_type`
image

**Review by sgurusamy-rli — COMMENTED** [review]
@emanuelvintila Changes look good. Couple of minor items:
1. only one of the requests of "Validations" have example requests it can be  removed. 
2. "Validations" folder can be moved to the bottom (after all the flows folders)

**Review by sgurusamy-rli — APPROVED** [review]

**Pull request merged**
